// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RecieveMessage() {
  return window['go']['main']['App']['RecieveMessage']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function Start_client(arg1, arg2) {
  return window['go']['main']['App']['Start_client'](arg1, arg2);
}
