// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddContact(arg1:string,arg2:string):Promise<boolean>;

export function GetContacts():Promise<Array<models.ContactsList>>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Start_client(arg1:string):Promise<void>;
